// log user in
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}
###

// create a new project
// Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzkxZmZlNTQzMmE4ZDFiNmFlNzdmODYiLCJpYXQiOjE2NzA1MTYxOTk0ODYsImV4cCI6MTY3MDUxNjI4NTg4Nn0.pTXXwzisaMm_sUChO4073TgEH5G0Vc_cQhi1Jfv6IHczBXrmPooPNS0xhldKcn_mvPLj4lORAFU8xyjIx1IlMaLQIg1FCVDqdIzb8yQXlHtNyiSNx0X9rWNPE4Jhy9fDyk6DNwKxtIbII7UgFgfeICAKkKHUXGSqxgbIKyYL5DC3xGpKE6si0l8rCp0GVCTPB1fSkgbzhu07vJIjQayzuGP1L2Qh2RhpibFMG-1cxORreXDdQqKvDHsiS8A1PxhJMOcHcA8GBkL-Af-f4YE55_ZNiI42yesEdhrsVqxDRJUKXV93pJNeU5G95-YGgXEFzgnxmJ8xqWirT7bvTZdbzrLv_CS2HOa_NFIHrxHEx7lgy5EP60M1k9Dol0QHG6w3FWSLxHAmy2E5HOEsGhf5Enm-Bxvo2d8Q7TuD8WL3o_YqTiCiohuefgmkbQW0DJDiJFQxSat0fmyC9khZvHGdsUkLICmJXFz805a2hhgPgA_C-2sOpHFOYEZ6TAt3yAcwgJFvEd-88HiTJmq47mDobeeEOzwatRMx47MhOUF35Lb7qtguGUCx9fq2Vwlk23YhbY9TQmNTL5K23Cp8GgyLolaKhper7wG2Wf06QspKlNPwTIy5d62MdMYLTuoqfZ_6GYS5wKwG_7r9wye22oNSpf9TfcNolLyQG04gZEHKl2E
